version: "3.7"
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: anyrec_db
      MYSQL_USER: anyrec_user
      MYSQL_PASSWORD: anyrec_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ../data:/var/lib/mysql
  server:
    build:
      context: ../api/src
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
    - "5000:5000"
    command: bash -c "sleep 3 && ./server"
    volumes:
      - ../seed_data:/root/seed_data
